name: Deploy to S3

on:
  push:
    branches:
      - main  # This triggers the action when you push to the main branch

permissions:
  contents: read  # Allow reading the repository's contents
  id-token: write  # Allow writing ID tokens for authentication
  s3: write  # Allow uploading files to S3

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job runs on the latest version of Ubuntu
    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up AWS credentials so GitHub can access your AWS account
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access key from GitHub secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Secret key from GitHub secrets
          aws-region: us-east-1  # Choose your preferred AWS region

      # Sync the local website files to the S3 bucket
      - name: Sync website to S3
        run: |
          aws s3 sync ./ s3://practice-web-app-bucket --exclude ".git/*" --delete  # Sync files from local to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Use the GitHub secret for AWS access
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Use the GitHub secret for AWS secret key
